version: "3"
services:
  dispatcher:
    build: dispatcher.dockerfile
    restart: always
    ports:
      - 8080:8080
  worker1:
    build: worker.dockerfile
    restart: always
    depends_on:
      - dispatcher
    ports:
      - 8081:8081
  worker2:
    build: worker.dockerfile
    restart: always
    depends_on:
      - dispatcher
    ports:
      - 8082:8082


volumes:
  - dispatcher
  - worker1
  - worker2
